### ISSUE TITLE
Run linting and formatting on CLI

### ISSUE THREAD

**Issue by andrelandgraf** [social-plan-it/plan-it-social-web#11]
Task: Run `npm run lint` on GitHub Action for open PRs and make PR check fail if linting or formatting error exists in PR-changed files.

## Motivation

We should not merge code that has existing formatting or lining issues. Instead, we should update our linting or formatting rules if we encounter issues.

Running the formatting and linting in the CLI ensures we never merge unformatted code.

**Comment by eiffelwong1** [comment]
completed
