### ISSUE TITLE
As a user, I want to be able to learn more about what is Social Plan it and how it works.

### ISSUE THREAD

**Issue by JacobBaqleh1** [social-plan-it/plan-it-social-web#12]

**Comment by CamilingJS** [comment]
![Image](https://github.com/social-plan-it/plan-it-social-web/assets/55357003/42541dbc-d650-4f6b-9368-d6a9ca7de7c0)

**Comment by CamilingJS** [comment]
- Navbar is up
- Hero #9  and Benefits section #19  pending PR 
- Upcoming events draft @ShowMale   #16

**Comment by eiffelwong1** [comment]
completed
