### ISSUE TITLE
Selecting a UI component library

### ISSUE THREAD

**Issue by andrelandgraf** [social-plan-it/plan-it-social-web#18]
We have to select a UI component library to use. There are different UI component libraries with different scopes. Some implement a certain given design system ([Material Design](https://m3.material.io/) -> [Material UI](https://mui.com/)), while others implement accessibility best practices but offer custom styling ([Headless UI](https://headlessui.com/)).

There are different trade-offs for both. What should we use? :)

**Comment by ShowMale** [comment]
Great idea Andre to discuss it here! 

* Can we still discuss other libraries? 
* The other question is, can we use a few UI libraries simultaneously?

We can start by listing the components needed for our project and checking the most relevant libraries. Also, good to define _requirements_ for the components. As we're building a social app, it definitely should be _accessible_. Other factors that come to my mind: the _ease of use_ and _documentation_. 

I haven't used any libraries in my projects yet but Radix and https://reakit.io/ fits well. Anyway, more information is needed. 
One more library to check out: https://ui.shadcn.com/

**Comment by andrelandgraf** [comment]
I would advise using only one library to avoid the complexity of overlapping components (which one do we use then?). Also, every library we add results in a bigger payload (website size) for the client (which slows our page load).

**Comment by andrelandgraf** [comment]
Any concerns with just starting with [Headless UI](https://headlessui.com/) and building our own custom components on top if we need anything else? What would be missing from Headless UI?

**Comment by CamilingJS** [comment]
> Any concerns with just starting with [Headless UI](https://headlessui.com/) and building our own custom components on top if we need anything else? What would be missing from Headless UI?

No concerns with Headless UI. LGTM!

**Comment by hrm123** [comment]
Should we create design system in figma? https://www.figma.com/blog/how-to-build-your-design-system-in-figma/

**Comment by ShowMale** [comment]
> Any concerns with just starting with [Headless UI](https://headlessui.com/) and building our own custom components on top if we need anything else? What would be missing from Headless UI?

Overall, it's a great choice. Only one concern, it has a limited amount of components.

**Comment by tonydangblog** [comment]
Since we're using TailwindCSS and HeadlessUI, would anyone be opposed to adding [@tailwindcss/forms](https://github.com/tailwindlabs/tailwindcss-forms) to our project? 

It's an official plugin from Tailwind that provides a basic reset for form styles, giving form elements a better base to override with Tailwind utility classes. I've used this in several projects and have had good experience with it. It also works nicely with HeadlessUI.

**Comment by andrelandgraf** [comment]
Happy to try out `@tailwindcss/forms`! Let's make sure to have our own wrapper components for each element! This way we don't expose the implementation details of the UI components to our routes and higher-level components and it will be easier to switch UI component library if needed.

**Comment by eiffelwong1** [comment]
selected headless UI and tailwindCSS (some functions might not be in headless UI, like calender. we can search for it in future)
