### ISSUE TITLE
As a user, I want to be able to find the groups, events, and communities that I am looking for.

### ISSUE THREAD

**Issue by CamilingJS** [social-plan-it/plan-it-social-web#20]
Task:

- Create a search page that shows search results (events, groups) 
- Add search bar to index (`/`) page (which loads search page) (see designs)
- Create search endpoint in Remix which searches for content in db

**Comment by andrelandgraf** [comment]
Refer to designs for latest version: https://www.figma.com/file/6e3cBuEHOIpWvqT31Zd29p/Social-Plan-it?type=design&node-id=0-1&t=YXPS7ywdQDQKpaYu-0

![Image](https://github.com/social-plan-it/plan-it-social-web/assets/15163028/ebe73eb8-be46-4634-805b-dc409b9d50f8)

**Comment by ShowMale** [comment]
Well done! 
I'm going to take over the "search" part.
