### ISSUE TITLE
Rename `Group` table (`Group` is a reserved keyword in MySQL)

### ISSUE THREAD

**Issue by tonydangblog** [social-plan-it/plan-it-social-web#47]
## Bug Description

Currently we have a table named `Group`.  `Group` is also a reserved keyword in MySQL. So, if we were to query the table from the PlanetScale console (i.e. `SELECT * FROM Group;`), an error is thrown.

Prisma seems to somehow be able to handle this without throwing an error, but perhaps it may be best practice to change the table name to a non-reserved keyword to avoid any potential issues in the future?

**Comment by andrelandgraf** [comment]
Interesting! Maybe Prisma escapes the table name or something. Anyhow, happy to rename it to `Community`!

**Comment by andrelandgraf** [comment]
ChatGPT to the rescue:

```
f you have a table named "Group," you can use backticks (`) in MySQL to escape the table name and avoid conflicts with reserved keywords. Here's how you can do it:

SELECT * FROM `Group`;

By enclosing the table name within backticks, you're telling MySQL to treat it as a literal identifier rather than a reserved keyword.

It's a good practice to use backticks when working with table or column names that might clash with reserved keywords or contain special characters. However, be mindful that backticks are specific to MySQL and might not work in other database systems. If you ever need to migrate your code to a different database system, you might need to adjust the syntax accordingly.
```

**Comment by tonydangblog** [comment]
Nice, I should have thought to ask ChatGPT!

I also just read that the same issue exists if we were to use PostgreSQL, except instead of backticks, we'd need to use quotes to escape. In any case, I think we can avoid these potential issues if we just rename the table so I'll go ahead and make a PR for it 🙂

**Comment by tonydangblog** [comment]
Per discussion in the Monday meetup call on 8/14/23, we decided to stick with `Group` for the table name rather than changing it to `Community`.

The reasons are because:
1. The name `Group` is shorter and clearer than `Community`.
2. Prisma already auto escapes the name for us so this is not an issue unless we're writing raw SQL statements, which is not preferred.
