### ISSUE TITLE
Group model in schema.prisma file needs additional fields 

### ISSUE THREAD

**Issue by CamilingJS** [social-plan-it/plan-it-social-web#98]
The following fields need to be added to the 'Group' model: 'imgUrl', 'imgAlt', 'headline', 'socialLinks' (array), 'location'. Afterward, update the database using the Prisma commands.

**Comment by shami-dev** [comment]
What do you think about these models? Do we miss something?
```
model Group {
  id          String  @id @default(uuid())
  name        String
  description String  @db.Text
  owner       String
  imgUrl      String?
  imgAlt      String?
  location    String?
  socialLinks Link[]
  events      Event[]
  users       User[]
}

model Link {
  id      String  @id @default(uuid())
  discord String?
  twitter String?

  Group   Group?  @relation(fields: [groupId], references: [id])
  groupId String?

  @@index([groupId])
}
```

**Comment by eiffelwong1** [comment]
do we need a separate table for Link tho?

can it be stored in Json formate? as we don't really need to query social media links separately and there are additional security benefits 

and with a separate link table, we should probably break down the social network name and network link,

**Comment by CamilingJS** [comment]
Looks good Shami. I believe member count could be inferred. 
I'd defer to @andrelandgraf on advice on how to handle social media links

**Comment by shami-dev** [comment]
> Looks good Shami. I believe member count could be inferred. I'd defer to @andrelandgraf on advice on how to handle social media links

Thanks! Even though data modelling is the essential part of building a web app, it is not my strongest skill 😅 I was thinking about calling @andrelandgraf and others, too; I tagged everyone in Discord.

**Comment by CamilingJS** [comment]
> ```
> model Group {
>   id          String  @id @default(uuid())
>   ...
>   socialLinks Json?
> }
> ```
> 
> prisma does support it: https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/working-with-json-fields
> 
> and within it simply puting the platform as key and link as value, like
> 
> ```
> {
> "facebook": "www.fb.com/12312313"
> "twitter": "www.x.com/123123"
> }
> ```
> 
> the reason for not needing a separate table is that there isn't a need to query on the social media link itself and it's always attached to the group. I personally think it can be basically be treated like the description of the group, just with json, which fits our programming need.

Awesome! I learned something knew!

**Comment by andrelandgraf** [comment]
One pro of using a separate table for social links would be if we want to reuse that table to be referenced from different entities (e.g., groups and events). Another pro of using a separate table would be to avoid fetching the links data for every request to groups, but I don't think that's the case for other. The downside of having two tables is that it's more complicated and you have to join the tables or make two request to get all the data.
